@startuml
title Koszyk Zakupowy Online

skinparam actorStyle awesome

actor "USER" as User
actor "SALESMAN" as Salesman
entity "DATAMANAGER" as datamanager
actor "USERNULL" as usernull

left to right direction

rectangle "Koszyk Zakupowy Online" {
  User --> (Przeglądanie sklepu)
  User --> (Wybieranie produktów)
  User --> (Wprowadzanie danych osobowych)
  User --> (Dodawanie produktów do koszyka)
  User --> (Zwiększanie/zmniejszanie wybranej ilości produktów oraz możliwość usunięcia wybranego produktu w koszyku)
  User --> (Wybór sposobu dostawy i płatności)
  User --> (Czyszczenie całego koszyka)
  User --> (Składanie zamówienia oraz otrzymywanie faktóry)
}
User --> (Logowanie/Wylogowywanie)
User --> (Rejestracja konta)
Salesman --> (Rejestracja konta)
Salesman --> (Logowanie/Wylogowywanie)

rectangle "Sprzedawca" {
  Salesman --> (Dodawanie/Usuwanie produktów)
  Salesman --> (Sprawdzanie ilości własnego produktu)
  Salesman --> (Zwiększanie zasobu wybranego własnego produktu)
  Salesman --> (Przedlądanie własnych produktów)
  Salesman --> (Sprawdzanie przychodu)
  Salesman --> (Sprawdzanie ilości sprzedanych produktów)
  Salesman --> (Sprawdzanie ilosci unikalnych produktów)
}

rectangle "DATAMANAGER" {
  datamanager --> (Zarządzanie danymi)
  datamanager --> (Aktualizuje liste wszystkich produktów)
  datamanager --> (Aktualizuje liste pracowników,użytkowników oraz zamówień)
  datamanager --> (Wyświetlanie komunikatów)
  datamanager --> (Zmiana wyświetlanych okienek/stron)
  datamanager --> (Aktualizuje na bierząco baze danych)
  datamanager --> (Zwraca aktualnego użytkownika/sprzedawce/wybrany produkt)
}

rectangle "USERNULL" {
    usernull --> (Przeglądnie sklepu)
}


@enduml
